name: "Deployment Action"
description: "Creates a GitHub Deployment status update"
author: "chrnorm"
inputs:
  state:
    description: "State for the deployment"
  token:
    description: "Github repository token"
  target-url:
    description: "Target url location"
  description:
    description: "Descriptive message about the deployment"
  deployment_id:
    description: "The ID of the deployment"
runs:
  using: "node12"
  main: "src/main.ts"
