name: "Deployment Status"
description: "Creates a GitHub Deployment status update"
author: "chrnorm"
branding:
  icon: arrow-up
  color: gray-dark
inputs:
  state:
    description: "State for the deployment"
    required: true
  token:
    description: "Github repository token"
    required: true
  target_url:
    description: "Target url location"
    required: false
  log_url:
    description: "Log url location"
    required: false
  environment_url:
    description: "Sets the URL for accessing your environment"
    required: false
  description:
    description: "Descriptive message about the deployment"
    required: false
  deployment_id:
    description: "The ID of the deployment"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
