name: 'Deployment Status'
description: 'Creates a GitHub Deployment status update'
author: 'chrnorm'
branding:
  icon: arrow-up
  color: gray-dark
inputs:
  repo:
    description: 'A custom repository to create the deployment for. Defaults to the repo the action is running in.'
    required: false
  owner:
    description: 'A custom owner to create the deployment for. Defaults to the repo owner the action is running in.'
    required: false
  state:
    description: 'State for the deployment'
    required: true
  token:
    description: 'Github repository token'
    required: true
  log-url:
    description: 'Sets the URL for deployment output'
    required: false
  environment-url:
    description: 'Sets the URL for accessing your environment'
    required: false
    default: ''
  environment:
    description: 'Name for the target deployment environment, which can be changed when setting a deploy status.'
    required: false
  description:
    description: 'Descriptive message about the deployment'
    required: false
  deployment-id:
    description: 'The ID of the deployment'
    required: true
  auto-inactive:
    description: "Adds a new inactive status to all prior non-transient, non-production environment deployments with the same repository and environment name as the created status's deployment. An inactive status is only added to deployments that had a success state."
    required: false
    default: 'true'
  github-base-url:
    description: 'Changes the API base URL for a GitHub Enterprise server.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
