name: "Deployment Action"
description: "Creates a GitHub Deployment status update"
author: "chrnorm"
inputs:
  state:
    description: "State for the deployment"
    required: true
  token:
    description: "Github repository token"
    required: true
  target_url:
    description: "Target url location"
    required: false
  description:
    description: "Descriptive message about the deployment"
    required: false
  deployment_id:
    description: "The ID of the deployment"
    required: true
runs:
  using: "node12"
  main: "lib/main.js"
